#define RASTERARCHIVE_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/KompasRasterArchiveTestFiles/"
#define RASTERARCHIVE_WRITE_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/KompasRasterArchiveTestFiles/"

#define RASTERMODEL_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/KompasRasterModelTestFiles/"
#define RASTERMODEL_WRITE_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/KompasRasterModelTestFiles/"
