#define RASTERARCHIVE_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Map2XRasterArchiveTestFiles/"
#define RASTERARCHIVE_WRITE_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/Map2XRasterArchiveTestFiles/"

#define RASTERMODEL_TEST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Map2XRasterModelTestFiles/"
#define RASTERMODEL_WRITE_TEST_DIR "${CMAKE_CURRENT_BINARY_DIR}/Map2XRasterModelTestFiles/"
